content-type:

  panchayat:
    input-files: null
    input-filter: ["/home/saba/projects/panchayat/panchayat/instance/*.yaml"]
    compressed-jsonl: "./khoj/embeddings/panchyat.jsonl.gz"
    embeddings-file: "./khoj/embeddings/panchayat_embeddings.pt"

search-type:
  symmetric:
    encoder: "sentence-transformers/all-MiniLM-L6-v2"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_directory: "~/.khoj/search/symmetric/"

  asymmetric:
    encoder: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_directory: "~/.khoj/search/asymmetric/"

  image:
    encoder: "sentence-transformers/clip-ViT-B-32"
    model_directory: "~/.khoj/search/image/"

processor:
