content-type:
  # The /data/folder/ prefix to the folders is here because this is
  # the directory to which the local files are copied in the docker-compose.
  # If changing, the docker-compose volumes should also be changed to match.
  yaml:
    input-files: null
    input-filter: "/home/saba/projects/panchayat/panchayat/instance/*.yaml"
    compressed-jsonl: "/data/embeddings/panchyat.jsonl.gz"
    embeddings-file: "/data/embeddings/panchayat_embeddings.pt"

search-type:
  symmetric:
    encoder: "sentence-transformers/all-MiniLM-L6-v2"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_directory: "/data/models/symmetric"

  asymmetric:
    encoder: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    model_directory: "/data/models/asymmetric"

processor:
  #conversation:
  #  openai-api-key: null
  #  conversation-logfile: "/data/embeddings/conversation_logs.json"